# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {};
in
{
  "pnpm-8.10.2" = nodeEnv.buildNodePackage {
    name = "pnpm";
    packageName = "pnpm";
    version = "8.10.2";
    src = fetchurl {
      url = "https://registry.npmjs.org/pnpm/-/pnpm-8.10.2.tgz";
      sha256 = "sha256-SHYJ6FfxwReAzJjdC/5MiosRx/I7w6RJOsfSY9b7bIw=";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Fast, disk space efficient package manager";
      homepage = "https://pnpm.io";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
