name: Build and Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-and-test:
    # ci is expensive, let's turn it off for now
    # strategy:
    #   matrix:
    #     os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ubuntu-latest-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ubuntu-latest-node-

      - run: npm ci

      - name: Check types and style
        run: npm run check

      - name: Test
        run: npm test
