name: Prepare Release

on:
  workflow_dispatch:

jobs:
  tag-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Run release-drafter to determine the next version
      - name: Determine next version from release-drafter
        id: release_drafter
        uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Use the output from the previous step to version the package
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Configure Git
        run: |
          git config user.name 'GitHub Actions'
          git config user.email 'eng+github@repl.it'

      - name: Bump version and create tag
        run: |
          # Get the tag_name output from the release-drafter step
          tag="${{ steps.release_drafter.outputs.tag_name }}"

          # Strip the 'v' prefix to get the bare version number
          version="${tag#v}"

          echo "Next version calculated by release-drafter is: $version"

          # Use the calculated version with npm version
          npm version "$version"

      - name: Push changes and tags
        run: git push --follow-tags
