name: 'Test Report'
on:
  workflow_run:
    workflows: ['build-and-test']
    types:
      - completed
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v1
        with:
          artifact: /test-results-(.*)/
          name: 'Tests ($1)'
          path: '*.xml'
          reporter: jest-junit
